DenyUsers root
Protocol 2
PasswordAuthentication no
PermitRootLogin no
AuthorizedKeysFIle .ssh/authorized_keys
LoginGraceTime 1m
MaxAuthTries 6
MaxSessions 10
PermitEmptyPasswords no
StrictModes yes
PubkeyAuthentication yes
AcceptEnv LANK LC_*
