- name: Install base packages
  apt:
      name:
        - htop
        - curl
        - git
        - vim
        - nano
        - sudo
        - openssh-server
        - tree
        - fastfetch
        - acl
        - systemd-resolved
        - bind9-dnsutils
      state: present
      update_cache: true
