- name: Install OpenSSH server
  apt:
    name:
      - openssh-server
    state: present

- name: Install SSH hardening config
  copy:
    src: 10-harden.conf
    dest: /etc/ssh/sshd_config.d/10-harden.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart ssh

- name: Enable OpenSSH
  systemd:
    name: ssh
    enabled: true
    state: started
