- hosts: servers
  become: true

  roles:
    - { role: users, tags: users }
    - { role: ssh, tags: ssh }
    - { role: firewall, tags: firewall }
    - { role: docker, tags: docker }
    - { role: std-packages, tags: pkg }
    - { role: unattended_upgrades, tags: pkg }
    - motd
    - timesync
